# Generated by Django 5.2.12 on 2026-03-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='tipo',
            field=models.CharField(choices=[('captura', 'Captura'), ('soltura', 'Soltura')], db_index=True, default='captura', max_length=20, verbose_name='Tipo da Foto'),
        ),
    ]
