# Generated by Django 5.2.12 on 2026-03-16 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('siop', '0002_foto_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='geolocalizacao',
            name='unique_geolocalizacao_por_objeto',
        ),
        migrations.AddConstraint(
            model_name='geolocalizacao',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'tipo', 'latitude', 'longitude'), name='unique_geolocalizacao_por_objeto'),
        ),
    ]
