# Generated by Django 5.2.12 on 2026-03-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siop', '0003_remove_geolocalizacao_unique_geolocalizacao_por_objeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='contato',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Província'),
        ),
    ]
