from .catalogos import (
    catalogo_areas,
    catalogo_encaminhamentos,
    catalogo_locais_por_area,
    catalogo_naturezas,
    catalogo_p1,
    catalogo_primeiros_socorros,
    catalogo_sexos,
    catalogo_tipos_ocorrencia,
    catalogo_tipos_pessoa,
    catalogo_tipos_por_natureza,
    catalogo_transportes,
)
from .ocorrencia import (
    anexo_download,
    ocorrencia,
    ocorrencia_edit,
    ocorrencia_export,
    ocorrencia_export_view_pdf,
    ocorrencia_list,
    ocorrencia_list_partial,
    ocorrencia_new,
    ocorrencia_view,
)

__all__ = [
    "anexo_download",
    "catalogo_areas",
    "catalogo_encaminhamentos",
    "catalogo_locais_por_area",
    "catalogo_naturezas",
    "catalogo_p1",
    "catalogo_primeiros_socorros",
    "catalogo_sexos",
    "catalogo_tipos_ocorrencia",
    "catalogo_tipos_pessoa",
    "catalogo_tipos_por_natureza",
    "catalogo_transportes",
    "ocorrencia",
    "ocorrencia_edit",
    "ocorrencia_export",
    "ocorrencia_export_view_pdf",
    "ocorrencia_list",
    "ocorrencia_list_partial",
    "ocorrencia_new",
    "ocorrencia_view",
]
